nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org/"

packageExtensions:
  "babel-plugin-module-resolver@*":
    peerDependencies:
      "@babel/core": "*"
  "next@*":
    peerDependencies:
      "babel-plugin-module-resolver": "*" 