services:
  - type: web
    name: trainers-memory
    env: python
    buildCommand: ./build.sh
    startCommand: python server.py
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
    envVars:
      - key: PORT
        value: 10000
      - key: USE_SQLITE
        value: "True"
      - key: DATABASE_URL
        value: sqlite:///./data/trainers_memory.db
      - key: SQLITE_URL
        value: sqlite:///./data/trainers_memory.db
      - key: ASYNC_SQLITE_URL
        value: sqlite+aiosqlite:///./data/trainers_memory.db
      - key: OPENAI_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: REDIS_URL
        value: "" 