services:
  - type: web
    name: trainers-memory
    env: python
    buildCommand: ./build.sh
    startCommand: python server.py
    envVars:
      - key: PORT
        value: 10000
      - key: DB_HOST
        value: dpg-cvadma7noe9s73f7ojag-a
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: trainers_memory_db
      - key: DB_USER
        value: trainers_memory_db_user
      - key: DB_PASS
        sync: false
      - key: DATABASE_URL
        value: postgresql://trainers_memory_db_user:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - key: OPENAI_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: REDIS_URL
        value: "" 