services:
  - type: web
    name: trainers-memory
    env: python
    buildCommand: ./build.sh
    startCommand: python server.py
    envVars:
      - key: PORT
        value: 10000
      - key: USE_SQLITE
        value: "True"
      - key: DATABASE_URL
        value: sqlite:///./trainers_memory.db
      - key: SQLITE_URL
        value: sqlite:///./trainers_memory.db
      - key: ASYNC_SQLITE_URL
        value: sqlite+aiosqlite:///./trainers_memory.db 