"""rename_workout_type_to_type

Revision ID: 062832f6fa7c
Revises: 11b146a41b82
Create Date: 2025-03-15 18:33:50.104553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062832f6fa7c'
down_revision = '11b146a41b82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('api_keys_client_id_fkey', 'api_keys', type_='foreignkey')
    op.create_foreign_key(None, 'api_keys', 'clients', ['client_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('exercises_workout_id_fkey', 'exercises', type_='foreignkey')
    op.create_foreign_key(None, 'exercises', 'workouts', ['workout_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('workouts_client_id_fkey', 'workouts', type_='foreignkey')
    op.create_foreign_key(None, 'workouts', 'clients', ['client_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    
    # Add the type column to the workouts table
    op.add_column('workouts', sa.Column('type', sa.String(255), nullable=True), schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the type column
    op.drop_column('workouts', 'type', schema='public')
    
    op.drop_constraint(None, 'workouts', schema='public', type_='foreignkey')
    op.create_foreign_key('workouts_client_id_fkey', 'workouts', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'exercises', schema='public', type_='foreignkey')
    op.create_foreign_key('exercises_workout_id_fkey', 'exercises', 'workouts', ['workout_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'api_keys', schema='public', type_='foreignkey')
    op.create_foreign_key('api_keys_client_id_fkey', 'api_keys', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ### 