"""create initial tables

Revision ID: 8e65eb38b292
Revises: 
Create Date: 2025-03-08 17:47:22.544624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e65eb38b292'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('api_keys_client_id_fkey', 'api_keys', type_='foreignkey')
    op.create_foreign_key(None, 'api_keys', 'clients', ['client_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('exercises_workout_id_fkey', 'exercises', type_='foreignkey')
    op.create_foreign_key(None, 'exercises', 'workouts', ['workout_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('workouts_client_id_fkey', 'workouts', type_='foreignkey')
    op.create_foreign_key(None, 'workouts', 'clients', ['client_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workouts', schema='public', type_='foreignkey')
    op.create_foreign_key('workouts_client_id_fkey', 'workouts', 'clients', ['client_id'], ['id'])
    op.drop_constraint(None, 'exercises', schema='public', type_='foreignkey')
    op.create_foreign_key('exercises_workout_id_fkey', 'exercises', 'workouts', ['workout_id'], ['id'])
    op.drop_constraint(None, 'api_keys', schema='public', type_='foreignkey')
    op.create_foreign_key('api_keys_client_id_fkey', 'api_keys', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ### 